### ISSUE TITLE
Package for F-Droid

### ISSUE THREAD

**Issue by ghost** [bamless/chromium-swe-updater#4]
[F-Droid](http://f-droid.org) is an app "store" for free/libre/open-source apps. We received a packaging request  at  https://gitlab.com/fdroid/rfp/issues/156 and would like to proceed with this. If you object publication, please let us know and we will remove this from our repository.

**Comment by bamless** [comment]
It's ok with me, you can publish it.

**Comment by ghost** [comment]
Thanks for the quick response.

**Comment by goyalyashpal** [comment]
coming from https://gitlab.com/fdroid/rfp/-/issues/156#note_30268270 - commenting to save the description for myself.
