### ISSUE TITLE
Update doesn't install

### ISSUE THREAD

**Issue by Madis0** [bamless/chromium-swe-updater#5]
Hello,
I tried this app today from FDroid and I was able to download but not install the SWE browser.
Here's my interaction:

1. When opening the app, it asks for storage permission. I allow
2. An update screen is shown, saying "_(today's date)_ build is available"
3. I tap the double arrow, a notification starts downloading and text is switched to "Downloading the update..."
4. When the download finishes, the notification disappears and the text says "No update available"
5. Tried rechecking for updates with the refresh icon, still no update available

Also tried clearing app's data several times, disabling ad blocker, removing another SWE browser, getting this app from XDA... still nothing. Using version 1.4 of the app on Android 7.1.1 (OnePlus 3).

**Comment by bamless** [comment]
First check if the "unknown sources" option in security settings is enabled. If it is, then please check if the browser apk is present in the "download" folder in internal memory (that's the default download path of the app).

**Comment by Madis0** [comment]
> First check if the "unknown sources" option in security settings is enabled.

Yes, otherwise I wouldn't have been able to use the updater at all.

> If it is, then please check if the browser apk is present in the "download" folder in internal memory

Yes, there is **chromium-swe.apk**.

**Comment by bamless** [comment]
That's weird, the system default apk installation process is supposed to start once the download is complete.
I'll need you to supply a logcat grabbed just after the download finishes to debug the issue further. To cause the app to reset and let you download the update again you can just clear its data in settings->app

**Comment by bamless** [comment]
Oh, and if in the meantime you want to start using the browser you can install the apk found in "download"

**Comment by Madis0** [comment]
Here you go (logcat removed for privacy). Seems like the error starts from time _23:32:35.709_.

```
05-26 23:32:35.709  1422 13497 W ActivityManager: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{b9cb73b 30371:com.google.android.packageinstaller/u0a13} (pid=30371, uid=10013) that is not exported from uid 16180
05-26 23:32:35.709  1422  1466 D StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{8414e32 u0 Starting com.google.android.packageinstaller} token=android.os.Binder@b2ac3d9 which=1
05-26 23:32:35.711 30371 30473 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
05-26 23:32:35.711 30371 30473 E AndroidRuntime: Process: com.google.android.packageinstaller, PID: 30371
05-26 23:32:35.711 30371 30473 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:325)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
05-26 23:32:35.711 30371 30473 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{b9cb73b 30371:com.google.android.packageinstaller/u0a13} (pid=30371, uid=10013) that is not exported from uid 16180
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1684)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1637)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:4407)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at android.app.ActivityThread.acquireProvider(ActivityThread.java:5646)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2265)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1647)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1170)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1023)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at android.content.ContentResolver.openInputStream(ContentResolver.java:743)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at com.android.packageinstaller.PackageInstallerActivity$StagingAsyncTask.doInBackground(PackageInstallerActivity.java:771)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at com.android.packageinstaller.PackageInstallerActivity$StagingAsyncTask.doInBackground(PackageInstallerActivity.java:762)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:305)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-26 23:32:35.711 30371 30473 E AndroidRuntime:        ... 4 more
05-26 23:32:35.711 30371 30473 D AppTracker: App Event: crash
```

**Comment by bamless** [comment]
Uninstall the app and install this one https://www.androidfilehost.com/?fid=817550096634772200. Let me know if now the update starts.

**Comment by Madis0** [comment]
Yes, this version did fix the issue!

**Comment by bamless** [comment]
So the problem seems to be that the package installer on your phone has a different package name than most android devices. "com.google.android.packageinstaller" instead of "com.android.packageinstaller". This caused a problem in file permissions. I'm going to push a new update to F-Droid so if you want to install from there check in a few days. Otherwise you can keep using this version i gave to you.
