### ISSUE TITLE
[Feature request] More control on background checks

### ISSUE THREAD

**Issue by walrus543** [bamless/chromium-swe-updater#6]
Hi,

We have no control on the background checks. I'd like to check new updates manually.
More options like every 1/2/4/12/24 hours could be useful for some users.

Thank you.

**Comment by jbz-dev** [comment]
+1

It could be a great addition for the app.

Otherwise nothing to say, it does the job :)

**Comment by bamless** [comment]
As i said on XDA when i'll have the time i'll implement this, you might have to wait a little more though.

**Comment by walrus543** [comment]
OK but why did you close the issue?
